# app/config/security.yml
security:
    # ...
    encoders:
        # ...
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    #    Symfony\Component\Security\Core\User\User:
    #        algorithm: bcrypt
    #        cost: 12

    providers:
        # ...
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    #    in_memory:
    #        memory:
    #            users:
    #                ryan:
    #                    password: ryanpass
    #                    roles: 'ROLE_USER'
    #                admin:
    #                    password: kitten
    #                    roles: 'ROLE_ADMIN'

    firewalls:
        # ...
        default:
            # all pages after the root require authentication
            pattern:    ^/
            http_basic: ~
            provider: db_provider

    access_control:
        # require ROLE_USER for this page
        - { path: ^/app/getUploadForm, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]





