<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{
    public function getAllArtistsPickerData() {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT a
            FROM AppBundle:Artist a
            ORDER BY a.id ASC
        ');

        $results = $query->getResult();

        $artists = array();

        if(count($results) > 0) {
            for ($i = 0; $i < count($results); $i++) {
                $artist = $results[$i];
                $artists[$artist->getId()] = $artist->getName();
            }
        }

        return $artists;
    }
}
